# Generated by Django 3.1.5 on 2021-03-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_sellerregister_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
