# Generated by Django 3.1.5 on 2021-03-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_admin_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerregister_tb',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
