# Generated by Django 3.1.5 on 2021-03-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_category_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingaddress', models.CharField(max_length=20)),
                ('contactnumber', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=20)),
                ('totalprice', models.CharField(max_length=20)),
            ],
        ),
    ]
