# Generated by Django 3.1.5 on 2021-03-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_cart_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart_tb',
        ),
    ]
