# Generated by Django 3.1.5 on 2021-03-22 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_category_tb'),
        ('seller', '0002_product_tb_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.category_tb'),
        ),
    ]
