# Generated by Django 3.1.5 on 2021-03-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_tracking_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking_tb',
            old_name='buyer_id',
            new_name='order_id',
        ),
    ]
