# Generated by Django 3.1.5 on 2021-04-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_order_tb'),
        ('seller', '0005_auto_20210330_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_tb',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buyer.order_tb'),
        ),
    ]
