# Generated by Django 3.1.5 on 2021-03-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0003_product_tb_category_id'),
        ('Admin', '0008_delete_cart_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingaddress', models.CharField(max_length=20)),
                ('contactnumber', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=20)),
                ('totalprice', models.CharField(max_length=20)),
                ('buyer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.register_tb')),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.product_tb')),
            ],
        ),
    ]
